version: "3"
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    image: jirathipk/postgres-vec-geo:latest
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password1234
    volumes:
      - database_volume:/var/lib/postgresql/data/

  backend:
    container_name: backend
    user: root
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: jirathipk/settle-aid-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_NAME=database
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password1234
      - DATABASE_USERNAME=db_user
      - SECRET_KEY=85a95f4921be5a5f0f122f2bde3f6609984d728867bb12ae713b5e32499b2204 #openssl rand -hex 32
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiamlyYXRoaXAiLCJhIjoiY2xsdTBoNzQ3MHdndzNzc3luaW03YmNseSJ9.CvqEW28-Dab5qUQ1MCQOgg

    depends_on:
      - db

volumes:
  database_volume:
