# Dockerfile.db

# Use the pgvector PostgreSQL image as the base
FROM ankane/pgvector

# Install the PostGIS extension
RUN apt-get update && apt-get  install -y postgresql-15-postgis-3

RUN apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8


CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]

