version: "3"
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    image: jirathipk/postgres-vec-geo:latest
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password1234
    volumes:
      - database_volume:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: redis-server --requirepass topmelloredis --loglevel verbose
    volumes:
      - redis_volume:/data

  backend:
    container_name: backend
    user: myuser
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: jirathipk/settle-aid-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
      - models_volume:/home/myuser/.cache/torch/sentence_transformers/
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_NAME=database
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password1234
      - DATABASE_USERNAME=db_user
      - SECRET_KEY=85a95f4921be5a5f0f122f2bde3f6609984d728867bb12ae713b5e32499b2204 #openssl rand -hex 32
      - REFRESH_SECRET_KEY=7d7c1acf8051446006174edf0f2c216d958bbafe701772e8291a9fcf97829691
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiamlyYXRoaXAiLCJhIjoiY2xsdTBoNzQ3MHdndzNzc3luaW03YmNseSJ9.CvqEW28-Dab5qUQ1MCQOgg
      - DOC_USERNAME=topmello
      - DOC_PASSWORD=da7da0df508738e37f18
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=topmelloredis
      - USER_CACHE_EXPIRY=3600
      - TRANSFORMERS_CACHE=/usr/src/app/transformers_cache
      - PYTEST_ADDOPTS="-o cache_dir=/usr/src/app/.pytest_cache"

    depends_on:
      - db
      - redis

volumes:
  database_volume:
  redis_volume:
  models_volume:
