# Dockerfile.db

# Use the pgvector PostgreSQL image as the base
FROM ankane/pgvector

# Install the PostGIS extension
RUN apt-get update && apt-get  install -y postgresql-15-postgis-3


CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]

