name: Python application test with Docker

on:
  push:
    branches: [main]

jobs:
  compose_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker images
        run: docker-compose -f docker-compose-dev.yaml down -v

      - name: Build the Docker images
        run: docker-compose -f docker-compose-dev.yaml up -d --build
      
      - name: Check Directory Permissions
        run: docker exec backend ls -la /usr/src/app

      - name: Set permissions for .pytest_cache and transformers_cache
        run: |
          docker exec -u root backend chmod 777 /usr/src/app/.pytest_cache
          docker exec -u root backend chmod 777 /usr/src/app/transformers_cache
      
      - name: Check Directory Permissions
        run: docker exec backend ls -la /usr/src/app

      - name: Check Running User
        run: docker exec backend id

      - name: Check database logs
        run: docker logs db
            
      - name: Run pytest
        run: docker exec backend pytest -vv -s

      - name: Stop and remove Docker container
        run: docker-compose -f docker-compose-dev.yaml down -v
