name: Python application test with Docker

on:
  push:
    branches: [main]

jobs:
  compose_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker images
        run: docker-compose -f docker-compose-dev.yaml up -d --build

      - name: Set Permissions for transformers_cache
        run: docker exec backend chmod -R 777 /usr/src/app/transformers_cache

      - name: Set Permissions for pytest_cache
        run: docker exec backend chmod -R 777 /usr/src/app/.pytest_cache

      - name: Check Directory Permissions
        run: docker exec backend ls -la /usr/src/app

      - name: Run pytest
        run: docker exec backend pytest

      - name: Stop and remove Docker container
        run: docker-compose -f docker-compose-dev.yaml down
