name: Build and Push Images - Dockerhub

on:
  workflow_dispatch:   # Manual trigger
  push:               # Push event
    branches:
      - deploy        # Only when pushed to 'deploy' branch

jobs:
  build_push_images:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile.db
            tag: ghcr.io/topmello/postgres-vec-geo:latest
          - dockerfile: Dockerfile.backend
            tag: ghcr.io/topmello/settle-aid-backend:latest


    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login Docker to GHCR
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Build and push Docker image to Dockerhub
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ matrix.tag }}
        context: .
        file: ${{ matrix.dockerfile }}

    
    


