name: CI/CD

on:
  push:
    branches:
      - deploy

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker images
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=-
        gcloud config set project YOUR_PROJECT_ID
        docker build -t australia-southeast2-docker.pkg.dev/fleet-fortress-395004/settle-aid/postgres-vec-geo . -f Dockerfile.db
        docker build -t australia-southeast2-docker.pkg.dev/fleet-fortress-395004/settle-aid/settle-aid-backend . -f Dockerfile.backend
        docker push australia-southeast2-docker.pkg.dev/fleet-fortress-395004/settle-aid/postgres-vec-geo
        docker push australia-southeast2-docker.pkg.dev/fleet-fortress-395004/settle-aid/settle-aid-backend

    - name: SSH and run docker-compose on GCP instance
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GCP_INSTANCE_IP }}
        username: github-action # The username associated with the SSH key you added to GCP.
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          docker-compose -f docker-compose-prod.yaml pull
          docker-compose -f docker-compose-prod.yaml up -d