name: Test

on:
  workflow_dispatch

jobs:
  test_github_action:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/593588930543/locations/global/workloadIdentityPools/githubactions/providers/github'
        service_account: '593588930543-compute@developer.gserviceaccount.com'
      


