name: Test

on:
  workflow_dispatch

jobs:
  test_github_action:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/593588930543/locations/global/workloadIdentityPools/githubactions/providers/github'
        service_account: 'github-actions@fleet-fortress-395004.iam.gserviceaccount.com'
        project_id: 'fleet-fortress-395004'
        token_format: 'access_token'
        access_token_lifetime: 300s

    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: australia-southeast2-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    
    - name: Build and push Docker images
      run: |
        docker build -t australia-southeast2-docker.pkg.dev/fleet-fortress-395004/settle-aid/postgres-vec-geo . -f Dockerfile.db
        docker push australia-southeast2-docker.pkg.dev/fleet-fortress-395004/settle-aid/postgres-vec-geo


